apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: user-service
          image: eu.gcr.io/s62-1-278920/userservice
          ports:
            - containerPort: 59502
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m