spring:
  profiles:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 49502

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:api
    username: sa
