spring:
  profiles:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
twitsec:
  rabbitmq:
    exchange: twitsec.exchange
    authqueue: auth.queue
    authroutingkey: auth
    tweetqueue: tweet.queue
    tweetroutingkey: tweet

server:
  port: 49502

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:api
    username: sa